.TH "md_README" 3 "Thu Mar 23 2023" "RGFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- Riley's Gui library FrameWork 
.PP
This library is meant to be used as a very small and flexable alternative library to GLFW\&.
.PP
This library
.PP
1) is single header and portable (written in C89 in mind) 2) is very small compared to other libraries 3) only depends on system API libraries, winapi, X11 4) let's you create a window with an opengl context and manage the window and it's events only with a few function calls
.PP
This library does not
.PP
1) Handle any rendering for you (other than creating your opengl context) 2) do anything above the bare minimum in terms of functionality 
